services:
  - type: web
    name: ben-whittaker-tech
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.18.2
      - key: NODE_ENV
        value: production
      - key: TZ
        value: Africa/Dar_es_Salaam
